In [1]:
from __future__ import division
import correlation as corr
import helpy
import matplotlib.pyplot as plt
import numpy as np

In [2]:
prefix = '/Users/zhejun/Documents/Result/0531/477/result'

In [3]:
meta = helpy.load_meta(prefix)
x0, y0, R = meta.get('boundary')
pdata, cdata = helpy.load_data(prefix, 'position corner')

In [4]:
def data_filter(data, x0, y0, inner, outer):
    x = data['x']
    y = data['y']
    position = [x - x0, y - y0]
    distance = np.hypot(*position)
    legal = np.where((distance < outer) & (distance > inner))
    return data[legal]

In [5]:
posdata = data_filter(pdata, x0, y0, R -40 , R)
cordata = data_filter(cdata, x0, y0, R -50, R + 5)

In [6]:
pfsets = helpy.load_framesets(posdata)

In [7]:
from tracks import find_tracks
from scipy.spatial import cKDTree as KDTree

In [8]:
pftrees = {f: KDTree(helpy.consecutive_fields_view(pfset, 'xy')) for f, pfset in pfsets.iteritems()}

In [9]:
posdata['id'] = np.arange(len(posdata))

In [1]:
trackids = find_tracks(posdata, maxdist=100, giveup=10, n=0, stub=0,
                cut=False, boundary=None, margin=0, pftrees = pftrees, pfsets = pfsets)

NameError: name 'find_tracks' is not defined

In [18]:
# 23 frame has 76 or more particles

In [26]:
place[0][0]

70382

In [20]:
place = np.where(trackids == 98)

In [27]:
print trackids[(place[0][0] - 20): (place[0][0]+ 20)]

[63 69 65 70 67 72 68 73 74 71  0  3  1  5  6  2  4  8  7 11 98 12  9 10 15
 13 17 14 19 16 21 18 23 20 25 22 27 24 29 26]


In [35]:
(0.0000001) ** (-0.59)

13489.62882591653

In [39]:
thisdot = posdata.item(80)

In [40]:
thisdot

(1, 32.18199920654297, 404.9739990234375, 39, 0.55517578125, 172, 80L)

In [41]:
frame = thisdot[0]
print frame

1


In [42]:
frame < 1

False

In [43]:
oldtree = pftrees[frame - 1]

In [45]:
len(oldtree.data)

75

In [46]:
thisdotxy = thisdot[1:3]

In [47]:
thisdot

(1, 32.18199920654297, 404.9739990234375, 39, 0.55517578125, 172, 80L)

In [48]:
thisdotxy

(32.18199920654297, 404.9739990234375)

In [49]:
maxdist_n = np.sqrt(1) * 20

In [91]:
mindist, mini = oldtree.query(thisdotxy, distance_upper_bound= maxdist_n)

In [51]:
mindist

0.019417020800322465

In [52]:
mini

5

In [53]:
mindist < maxdist_n

True

In [54]:
closest = pfsets[frame-1].item(mini)

In [55]:
closest

(0, 32.20100021362305, 404.9700012207031, 41, 0.53515625, 170, 5L)

In [62]:
curtree = pftrees[frame]

In [57]:
curtree.data

array([[  22.92700005,  482.5329895 ],
       [  22.61499977,  524.92602539],
       [  26.06500053,  565.04199219],
       [  27.24900055,  442.68798828],
       [  31.43600082,  603.1619873 ],
       [  32.18199921,  404.97399902],
       [  42.75299835,  365.95300293],
       [  42.68099976,  642.        ],
       [  46.78300095,  614.08502197],
       [  56.72000122,  325.32699585],
       [  55.65800095,  680.05297852],
       [  72.22100067,  716.75897217],
       [  73.52899933,  289.98999023],
       [  91.39499664,  255.33500671],
       [  93.09899902,  754.80401611],
       [ 115.07099915,  786.84399414],
       [ 115.99199677,  218.80000305],
       [ 138.32099915,  817.8449707 ],
       [ 140.30499268,  188.65400696],
       [ 167.14599609,  849.37298584],
       [ 169.71800232,  157.29200745],
       [ 197.40299988,  873.44598389],
       [ 201.40100098,  131.15699768],
       [ 229.19999695,  895.08099365],
       [ 232.6499939 ,  107.10399628],
       [ 259.14401245,  9

In [63]:
frame 

1

In [64]:
closestxy = closest[1:3]

In [65]:
closestxy

(32.20100021362305, 404.9700012207031)

In [73]:
mindist2, mini2 = curtree.query(closestxy, distance_upper_bound=mindist)

In [74]:
mindist2

inf

In [75]:
mindist

0.019417020800322465

In [76]:
mindist2 < mindist

False

In [77]:
trackids = -np.ones(posdata.shape, dtype = int)

In [80]:
trackids[0:79]= list(range(79))

In [81]:
trackids

array([ 0,  1,  2, ..., -1, -1, -1])

In [82]:
oldtrackid = trackids[closest[-1]]

In [83]:
oldtrackid

5

In [84]:
closest[-1]

5L

In [87]:
p = None

In [88]:
p is None

True

In [89]:
max(trackids)

78

In [90]:
trackids

array([ 0,  1,  2, ..., -1, -1, -1])

In [93]:
max(trackids)

98